In [1]:
from numpy import random
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# df=sns.get_dataset_names()
# df

In [3]:
data=sns.load_dataset('flights')

In [4]:
data

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [5]:
data=data[data['month']!='Jan']

In [6]:
data

year month  passengers
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
5    1949   Jun         135
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[132 rows x 3 columns]

In [7]:
data.isnull().sum()

year          0
month         0
passengers    0
dtype: int64

In [8]:
d1=sns.load_dataset('titanic')

In [9]:
d1

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [10]:
d1.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [11]:
nn=d1['age'].median()
nn

28.0

In [12]:
d1['age'].fillna(nn,inplace=True)

In [13]:
d1['age'].unique()

array([22.  , 38.  , 26.  , 35.  , 28.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  ,  8.  ,
       19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  , 49.  ,
       29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  , 16.  ,
       25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [14]:
d1['age'].mode()

0    28.0
Name: age, dtype: float64

In [15]:
n=d1['age'].value_counts()[1]

In [16]:
n

7

In [17]:
d1.shape

(891, 15)

In [18]:
d1.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [19]:
list(d1.columns)

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

In [20]:
d1.drop(columns=['who'], inplace=True)
d1.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'adult_male', 'deck', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [21]:
d1.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

In [22]:
d1.drop(columns=['deck'],inplace=True)

In [23]:
d1['age'].fillna(d1['age'].median(),inplace=True)

In [24]:
d1.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [25]:
d1.dropna(how='any',inplace=True)

In [26]:
d1.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [27]:
d1.duplicated().sum()

116

In [28]:
d1.shape

(889, 13)

In [29]:
d1.drop_duplicates(inplace=True)

In [30]:
d1.shape

(773, 13)

In [31]:
gr=d1.groupby('pclass')

In [32]:
gr.get_group(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third   
2           1       3  female  26.0      0      0   7.9250        S  Third   
4           0       3    male  35.0      0      0   8.0500        S  Third   
5           0       3    male  28.0      0      0   8.4583        Q  Third   
7           0       3    male   2.0      3      1  21.0750        S  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
881         0       3    male  33.0      0      0   7.8958        S  Third   
882         0       3  female  22.0      0      0  10.5167        S  Third   
885         0       3  female  39.0      0      5  29.1250        Q  Third   
888         0       3  female  28.0      1      2  23.4500        S  Third   
890         0       3    male  32.0      0      0   7.7500        Q  Third   

     adult_male  embark_town alive  alone  
0          True  Southampton    no  False  
2         False  Southampton   yes   True  
4          True  Southampton    no   True  
5          True   Queenstown    no   True  
7         False  Southampton    no  False  
..          ...          ...   ...    ...  
881        True  Southampton    no   True  
882       False  Southampton    no   True  
885       False   Queenstown    no  False  
888       False  Southampton    no  False  
890        True   Queenstown    no   True  

[401 rows x 13 columns]

In [33]:
gr1=d1.groupby('embark_town')

In [88]:
gr1

In [34]:
gr1['age'].aggregate(np.mean)

embark_town
Cherbourg      30.562387
Queenstown     28.043103
Southampton    29.395982
Name: age, dtype: float64

In [35]:
dd=d1.loc[(d1['embark_town']=='Southampton')&(d1['age']>20)]

In [36]:
dd.tail()

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
880         1       2  female  25.0      0      1  26.0000        S  Second   
881         0       3    male  33.0      0      0   7.8958        S   Third   
882         0       3  female  22.0      0      0  10.5167        S   Third   
883         0       2    male  28.0      0      0  10.5000        S  Second   
888         0       3  female  28.0      1      2  23.4500        S   Third   

     adult_male  embark_town alive  alone  
880       False  Southampton   yes  False  
881        True  Southampton    no   True  
882       False  Southampton    no   True  
883        True  Southampton    no   True  
888       False  Southampton    no  False

In [37]:
d1.shape

(773, 13)

In [38]:
dd.shape

(429, 13)

In [39]:
d1['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown'], dtype=object)

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [41]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.ndim

2

In [43]:
arr[1]+arr[5]

8

In [44]:
a[0,1]

2

In [45]:
a1=np.array([1,2,3,4,5,6,7,8,9])
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [47]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
a2[1,0:3]

array([5, 6, 7])

In [91]:
a2[0:2,1::2]

array([[31,  4],
       [ 6,  8]])

In [50]:
x=a2.copy()
y=a2.view()

x.base
y.base

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
x[0]=31
x

array([[31, 31, 31, 31],
       [ 5,  6,  7,  8]])

In [52]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
y[0,1]=31
y

array([[ 1, 31,  3,  4],
       [ 5,  6,  7,  8]])

In [54]:
a2

array([[ 1, 31,  3,  4],
       [ 5,  6,  7,  8]])

In [55]:
a2.shape

(2, 4)

In [56]:
a2.reshape(4,2)

array([[ 1, 31],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [57]:
a2.reshape(-1)

array([ 1, 31,  3,  4,  5,  6,  7,  8])

In [58]:
for x in a2:
    print(x)

[ 1 31  3  4]
[5 6 7 8]


In [59]:
for x in a2:
    for y in x:
        print(y)

1
31
3
4
5
6
7
8


In [60]:
for x in np.nditer(a2):
    print(x)

1
31
3
4
5
6
7
8


In [61]:
a2[:,::-1]

array([[ 4,  3, 31,  1],
       [ 8,  7,  6,  5]])

In [62]:
a3=np.array([1,2,3,4])
a4=np.array([1,2,3,4])
aa=np.concatenate((a3,a4))
aa

array([1, 2, 3, 4, 1, 2, 3, 4])

In [63]:
a5=np.array([[1,2,3],[0,0,0]])
a6=np.array([[1,1,1],[1,2,3]])
aaa=np.concatenate((a5,a6),axis=1)
aaa

array([[1, 2, 3, 1, 1, 1],
       [0, 0, 0, 1, 2, 3]])

In [64]:
aaaa=np.concatenate((a5,a6),axis=0)
aaaa

array([[1, 2, 3],
       [0, 0, 0],
       [1, 1, 1],
       [1, 2, 3]])

In [3]:
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b1=np.array_split(b,4)
b1

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [5]:
x=np.where(b==3)
print(x[0])

[2]


In [92]:
y=np.searchsorted(b,8)
y

7

In [68]:
c=np.array([4,3,5,6,2,1,7,8])
x=np.sort(c)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
d=np.ones([5,2])
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
d1=np.zeros([3,3])
d1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
e=np.random.rand(10)
e

array([0.91209393, 0.54471943, 0.85651244, 0.8405483 , 0.80617653,
       0.41022353, 0.92129163, 0.86229827, 0.45392597, 0.88896277])

In [72]:
e1=np.random.rand()
e1

0.5870898854264794

In [73]:
e2=np.random.randn()
e2

0.19493607865741341

In [74]:
e3=np.random.randint(4)
e3

3

In [75]:
f=np.random.randint(100,size=(10,10))
f

array([[14, 45, 18, 89, 93,  3, 75, 25, 22, 51],
       [65,  0, 90, 12, 70, 24, 44, 22, 90, 91],
       [33, 78, 67, 53, 84, 56, 76, 92, 12, 19],
       [97, 17, 65, 18, 91,  0, 32, 89, 69, 51],
       [30, 46, 31, 88, 21, 48, 87, 75, 21, 58],
       [49, 75, 21,  0, 27, 21, 68,  8, 70, 98],
       [77,  6, 39, 72, 93, 30,  5,  8, 28, 29],
       [18, 19, 88, 46, 73,  7, 78, 93, 83, 15],
       [67, 77,  1, 13, 74, 21, 36, 12, 29,  7],
       [89, 22, 50, 81, 70,  6,  8,  5,  3,  9]])

In [76]:
g=np.random.rand(10,10)
g

array([[0.57743381, 0.64043223, 0.51380927, 0.09608488, 0.28763761,
        0.73871255, 0.82087076, 0.01525251, 0.12989254, 0.92176849],
       [0.73458964, 0.06216336, 0.44543323, 0.19352518, 0.53865536,
        0.2442171 , 0.86876673, 0.9426097 , 0.18480318, 0.66723951],
       [0.95096557, 0.23787415, 0.4165042 , 0.62269785, 0.3175304 ,
        0.58044825, 0.65457352, 0.19798344, 0.74931622, 0.85850591],
       [0.99992537, 0.77401631, 0.44878607, 0.02815702, 0.25167796,
        0.49346867, 0.19343765, 0.20638564, 0.79105226, 0.73237188],
       [0.8925056 , 0.8798791 , 0.27486558, 0.83111876, 0.50408573,
        0.72896643, 0.62848681, 0.71971529, 0.01325437, 0.73732933],
       [0.07121287, 0.77291053, 0.22677062, 0.77118177, 0.204345  ,
        0.01162732, 0.24525618, 0.19541978, 0.57526569, 0.52903211],
       [0.63328078, 0.86819261, 0.67669093, 0.10460038, 0.2257584 ,
        0.80012238, 0.2709197 , 0.95386229, 0.52858943, 0.47782777],
       [0.01292832, 0.98419075, 0.2588460

In [77]:
h=np.array([1,2,3,4,5,6,7])
x=random.choice(h)
x

2

In [78]:
np.random.seed(10)
i=np.random.randint(0,100,size=(3,4))
i

array([[ 9, 15, 64, 28],
       [89, 93, 29,  8],
       [73,  0, 40, 36]])

In [95]:
j=np.array([1,2,3,4,5])
random.shuffle(j)
j

array([2, 1, 3, 5, 4])

In [94]:
k=np.array([1,2,3,4,5,6])
random.permutation(k)

array([6, 2, 5, 4, 3, 1])

In [81]:
np.random.seed(10)
l=np.random.randint(0,101,size=(10,10))
l

array([[  9, 100,  15,  64,  28,  89,  93,  29,   8,  73],
       [  0,  40,  36,  16, 100,  11,  54,  88,  62,  33],
       [ 72, 100,  78,  49,  51,  54,  77,  69,  13,  25],
       [ 13,  92,  86,  30,  30,  89,  12,  65,  31,  57],
       [ 36,  27,  18,  93,  77,  22,  23,  94,  11,  28],
       [ 74,  88,   9,  15,  18,  80,  71,  88,  11,  17],
       [ 46,   7,  75,  28,  33,  84,  96,  88,  44,   5],
       [  4,  71,  88,  88,  50,  54,  34,  15,  77,  88],
       [ 15,   6,  85,  22,  11,  12,  92,  96,  62,  57],
       [ 79,  42,  57,  97,  50,  45,  40,  89,  73,  37]])

In [102]:
l1=np.reshape(l,(-1,4))

In [103]:
l1

array([[  9, 100,  15,  64],
       [ 28,  89,  93,  29],
       [  8,  73,   0,  40],
       [ 36,  16, 100,  11],
       [ 54,  88,  62,  33],
       [ 72, 100,  78,  49],
       [ 51,  54,  77,  69],
       [ 13,  25,  13,  92],
       [ 86,  30,  30,  89],
       [ 12,  65,  31,  57],
       [ 36,  27,  18,  93],
       [ 77,  22,  23,  94],
       [ 11,  28,  74,  88],
       [  9,  15,  18,  80],
       [ 71,  88,  11,  17],
       [ 46,   7,  75,  28],
       [ 33,  84,  96,  88],
       [ 44,   5,   4,  71],
       [ 88,  88,  50,  54],
       [ 34,  15,  77,  88],
       [ 15,   6,  85,  22],
       [ 11,  12,  92,  96],
       [ 62,  57,  79,  42],
       [ 57,  97,  50,  45],
       [ 40,  89,  73,  37]])

In [84]:
df=pd.DataFrame(l1)

In [85]:
df.head(3)

0    1
0   9  100
1  15   64
2  28   89

In [122]:
np.random.seed(10)
data=np.random.randint(0,100,size=(10,4))
data

array([[ 9, 15, 64, 28],
       [89, 93, 29,  8],
       [73,  0, 40, 36],
       [16, 11, 54, 88],
       [62, 33, 72, 78],
       [49, 51, 54, 77],
       [69, 13, 25, 13],
       [92, 86, 30, 30],
       [89, 12, 65, 31],
       [57, 36, 27, 18]])

In [1]:
data1=pd.DataFrame(data,index=range(1,len(data)+1),columns=["A","B","C","D"])

NameError: name 'pd' is not defined

In [1]:
data1

NameError: name 'data1' is not defined

In [5]:
import numpy as np
d=np.random.randint(0,111,size=(10,2))
d

array([[  3,  27],
       [ 50,  92],
       [ 88,   7],
       [100, 108],
       [ 50,  59],
       [ 87,   4],
       [ 82,   3],
       [ 51,  76],
       [ 21,   6],
       [ 19, 100]])

In [6]:
for i in np.nditer(d):
    print(i)

3
27
50
92
88
7
100
108
50
59
87
4
82
3
51
76
21
6
19
100


In [8]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [10]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 7 7 7 5 7 7 7 3 7 5 5 7 3 5 7 7 7 5 7 3 7 7 5 7 7 7 3 7 7 5 5 7 7 7 7 7
 7 3 5 7 5 5 7 7 5 5 7 7 7 7 5 7 7 5 7 7 5 5 3 7 5 5 5 7 7 5 5 7 7 5 7 7 7
 5 5 3 7 7 5 5 5 7 5 5 7 5 3 5 7 7 7 5 5 3 7 7 7 5 7]


In [1]:
!jt r

usage: jt [-h] [-l] [-t THEME] [-f MONOFONT] [-fs MONOSIZE] [-nf NBFONT]
          [-nfs NBFONTSIZE] [-tf TCFONT] [-tfs TCFONTSIZE] [-dfs DFFONTSIZE]
          [-ofs OUTFONTSIZE] [-mathfs MATHFONTSIZE] [-m MARGINS]
          [-cursw CURSORWIDTH] [-cursc CURSORCOLOR] [-cellw CELLWIDTH]
          [-lineh LINEHEIGHT] [-altp] [-altmd] [-altout] [-P] [-T] [-N] [-kl]
          [-vim] [-r] [-dfonts]
jt: error: unrecognized arguments: r


In [2]:
!jt -r

Reset css and font defaults in:
C:\Users\melbi\.jupyter\custom &
C:\Users\melbi\AppData\Roaming\jupyter\nbextensions
