Tokenisation

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
txt='Anatomically modern humans first arrived on the Indian subcontinent between 73,000 and 55,000 years ago.[1] The earliest known human remains in South Asia date to 30,000 years ago. Sedentariness began in South Asia around 7000 BCE;[2] by 4500 BCE, settled life had spread,[2] and gradually evolved into the Indus Valley Civilisation, which flourished between 2500 BCE and 1900 BCE in present-day Pakistan and north-western India. Early in the second millennium BCE, persistent drought caused the population of the Indus Valley to scatter from large urban centres to villages. '
word_tokenize(txt)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['Anatomically',
 'modern',
 'humans',
 'first',
 'arrived',
 'on',
 'the',
 'Indian',
 'subcontinent',
 'between',
 '73,000',
 'and',
 '55,000',
 'years',
 'ago',
 '.',
 '[',
 '1',
 ']',
 'The',
 'earliest',
 'known',
 'human',
 'remains',
 'in',
 'South',
 'Asia',
 'date',
 'to',
 '30,000',
 'years',
 'ago',
 '.',
 'Sedentariness',
 'began',
 'in',
 'South',
 'Asia',
 'around',
 '7000',
 'BCE',
 ';',
 '[',
 '2',
 ']',
 'by',
 '4500',
 'BCE',
 ',',
 'settled',
 'life',
 'had',
 'spread',
 ',',
 '[',
 '2',
 ']',
 'and',
 'gradually',
 'evolved',
 'into',
 'the',
 'Indus',
 'Valley',
 'Civilisation',
 ',',
 'which',
 'flourished',
 'between',
 '2500',
 'BCE',
 'and',
 '1900',
 'BCE',
 'in',
 'present-day',
 'Pakistan',
 'and',
 'north-western',
 'India',
 '.',
 'Early',
 'in',
 'the',
 'second',
 'millennium',
 'BCE',
 ',',
 'persistent',
 'drought',
 'caused',
 'the',
 'population',
 'of',
 'the',
 'Indus',
 'Valley',
 'to',
 'scatter',
 'from',
 'large',
 'urban',
 'centres',
 'to',
 

In [ ]:
from nltk.tokenize import sent_tokenize

sent_tokenize(txt)

['Anatomically modern humans first arrived on the Indian subcontinent between 73,000 and 55,000 years ago.',
 '[1] The earliest known human remains in South Asia date to 30,000 years ago.',
 'Sedentariness began in South Asia around 7000 BCE;[2] by 4500 BCE, settled life had spread,[2] and gradually evolved into the Indus Valley Civilisation, which flourished between 2500 BCE and 1900 BCE in present-day Pakistan and north-western India.',
 'Early in the second millennium BCE, persistent drought caused the population of the Indus Valley to scatter from large urban centres to villages.']

In [ ]:
import nltk
from nltk.stem import PorterStemmer

porter_stemmer=PorterStemmer()

content=' the runner was running more faster than others'

words=nltk.word_tokenize(content)

result=[porter_stemmer.stem(word) for word in words]

print(result)

['the', 'runner', 'wa', 'run', 'more', 'faster', 'than', 'other']


In [ ]:
from nltk.stem import SnowballStemmer

snowball_=SnowballStemmer('english')

re=[snowball_.stem(i) for i in words]
print(re)

['the', 'runner', 'was', 'run', 'more', 'faster', 'than', 'other']


In [ ]:
from nltk.stem import WordNetLemmatizer

lemma=WordNetLemmatizer()

print('returns',lemma.lemmatize('returns'))
print('better',lemma.lemmatize('good',pos='a'))

returns return
better good


In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

content='Anatomically modern humans first arrived on the Indian subcontinent between 73,000 and 55,000 years ago.[1] The earliest known human remains in South Asia date to 30,000 years ago. Sedentariness began in South Asia around 7000 BCE;[2] by 4500 BCE, settled life had spread,[2] and gradually evolved into the Indus Valley Civilisation, which flourished between 2500 BCE and 1900 BCE in present-day Pakistan and north-western India. Early in the second millennium BCE, persistent drought caused the population of the Indus Valley to scatter from large urban centres to villages. '

doc=nlp(content)
for ent in doc.ents:
  print(ent.text,'|',ent.start_char,'|',ent.end_char,'|',ent.label_)

first | 27 | 32 | ORDINAL
Indian | 48 | 54 | NORP
between 73,000 and 55,000 years | 68 | 99 | CARDINAL
South Asia | 144 | 154 | LOC
30,000 years ago | 163 | 179 | DATE
Sedentariness | 181 | 194 | PERSON
South Asia | 204 | 214 | LOC
around 7000 | 215 | 226 | CARDINAL
4500 | 238 | 242 | CARDINAL
BCE | 243 | 246 | ORG
the Indus Valley Civilisation | 303 | 332 | ORG
2500 | 359 | 363 | CARDINAL
BCE | 364 | 367 | ORG
1900 | 372 | 376 | CARDINAL
BCE | 377 | 380 | ORG
present-day | 384 | 395 | DATE
Pakistan | 396 | 404 | GPE
India | 423 | 428 | GPE
the second | 439 | 449 | DATE
BCE | 461 | 464 | ORG
the Indus Valley | 510 | 526 | LOC


In [2]:
from spacy import displacy
displacy.render(doc,style='ent')

NameError: name 'doc' is not defined

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

d0='hello, my name is melbin mathew'
d1='melbin mathew'
d2='hello'

string=[d0,d1,d2]

result=tfidf.fit_transform(string)

print(tfidf.vocabulary_)
print(result.toarray())
print(result)

{'hello': 0, 'my': 4, 'name': 5, 'is': 1, 'melbin': 3, 'mathew': 2}
[[0.34949812 0.45954803 0.34949812 0.34949812 0.45954803 0.45954803]
 [0.         0.         0.70710678 0.70710678 0.         0.        ]
 [1.         0.         0.         0.         0.         0.        ]]
  (0, 2)	0.3494981241087058
  (0, 3)	0.3494981241087058
  (0, 1)	0.45954803293870056
  (0, 5)	0.45954803293870056
  (0, 4)	0.45954803293870056
  (0, 0)	0.3494981241087058
  (1, 2)	0.7071067811865476
  (1, 3)	0.7071067811865476
  (2, 0)	1.0


In [ ]:
import re
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()

txt=[ "Natural Language Processing is fun!",
    "I love learning about Natural Language Processing.",
    "Text analysis with Python is interesting."]

def preprocessing(txt):
  txt=txt.lower()
  txt=re.sub(r'[^a-z\s]',' ',txt)
  txt=re.sub(r'\s+',' ',txt)
  return txt.strip()

processed_txt=[preprocessing(doc) for doc in txt]

x=vectorizer.fit_transform(processed_txt)

print(vectorizer.vocabulary_)

print(x.toarray())

{'natural': 8, 'language': 5, 'processing': 9, 'is': 4, 'fun': 2, 'love': 7, 'learning': 6, 'about': 0, 'text': 11, 'analysis': 1, 'with': 12, 'python': 10, 'interesting': 3}
[[0 0 1 0 1 1 0 0 1 1 0 0 0]
 [1 0 0 0 0 1 1 1 1 1 0 0 0]
 [0 1 0 1 1 0 0 0 0 0 1 1 1]]


In [ ]:
import numpy as np
import pandas as pd

email=pd.read_csv('/content/drive/MyDrive/Data Sets/email.csv')
email.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
email.Category.unique()

array(['ham', 'spam', '{"mode":"full"'], dtype=object)

In [ ]:
email.isna().sum()

Category    0
Message     0
dtype: int64

In [ ]:
import nltk
import re
def preprocessing(txt):
  txt=txt.lower()
  txt=re.sub(r'[^a-z\s]',' ',txt)
  txt=re.sub(r'\s+',' ',txt)

  return txt.strip()

In [ ]:
email['labels']=email['Category'].map({'ham':0,'spam':1})

email['features']=email['Message'].apply(preprocessing)
email.head()

Category                                            Message  labels  \
0      ham  Go until jurong point, crazy.. Available only ...     0.0   
1      ham                      Ok lar... Joking wif u oni...     0.0   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1.0   
3      ham  U dun say so early hor... U c already then say...     0.0   
4      ham  Nah I don't think he goes to usf, he lives aro...     0.0   

                                            features  
0  go until jurong point crazy available only in ...  
1                            ok lar joking wif u oni  
2  free entry in a wkly comp to win fa cup final ...  
3        u dun say so early hor u c already then say  
4  nah i don t think he goes to usf he lives arou...

In [ ]:
email.isna().sum()

Category    0
Message     0
labels      1
features    0
dtype: int64

In [ ]:
email=email.dropna()

In [ ]:
email.isna().sum()

Category    0
Message     0
labels      0
features    0
dtype: int64

In [ ]:
email['labels']=email['labels'].astype(int)
email.head()

Category                                            Message  labels  \
0      ham  Go until jurong point, crazy.. Available only ...       0   
1      ham                      Ok lar... Joking wif u oni...       0   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...       1   
3      ham  U dun say so early hor... U c already then say...       0   
4      ham  Nah I don't think he goes to usf, he lives aro...       0   

                                            features  
0  go until jurong point crazy available only in ...  
1                            ok lar joking wif u oni  
2  free entry in a wkly comp to win fa cup final ...  
3        u dun say so early hor u c already then say  
4  nah i don t think he goes to usf he lives arou...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

X=email['features']
y=email['labels']

from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y, test_size=0.2,random_state=42)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

cls=Pipeline([
    ('tfidf',tfidf),
    ('Logistic regression',LogisticRegression())
])
cls.fit(Xtrain,ytrain)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('Logistic regression', LogisticRegression())])

In [ ]:
ypred=cls.predict(Xtest)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
print(classification_report(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(accuracy_score(ytest,ypred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       966
           1       1.00      0.79      0.88       149

    accuracy                           0.97      1115
   macro avg       0.98      0.89      0.93      1115
weighted avg       0.97      0.97      0.97      1115

[[966   0]
 [ 32 117]]
0.9713004484304932
