Numpy -Numerical Python

ndarry-n- dimensional array

In [1]:
import numpy as np
from numpy import random

In [2]:
np1=np.array([0,1,2,3,4,5,6,7,8,9])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np1.shape

(10,)

In [4]:
#Arange
np2=np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Step
np3=np.arange(0,10,2)
np3

array([0, 2, 4, 6, 8])

In [6]:
#Zeros
np4=np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#Multi-dimensional
np5=np.zeros((2,10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
#Full
np6=np.full((10),6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [9]:
#Multi-dimensional
np7=np.full((2,10),7)
np7

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [10]:
# Convert python list to np

my_list=[1,2,3,4,5,6]
np8=np.array(my_list)
np8

array([1, 2, 3, 4, 5, 6])

In [11]:
#Slicing Numpy Array
   
np1=np.array([1,2,3,4,5,6,7,8,9])
#Return 2,3,4,5
np1[1:5]

array([2, 3, 4, 5])

In [12]:
#Return till the end of the array?

np1[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#Return Negative slicing

np1[-3:-1]

array([7, 8])

In [14]:
#Slicing with Steps

np1[1::2]

array([2, 4, 6, 8])

In [15]:
np1[::2]

array([1, 3, 5, 7, 9])

In [16]:
#Slice 2-D array
random.seed(12)
np2=np.random.randint(0,10,size=(2,10))
np2

array([[6, 1, 2, 3, 3, 0, 6, 1, 4, 5],
       [9, 2, 6, 0, 5, 8, 2, 9, 3, 4]])

In [17]:
np2[1,2]

6

In [18]:
np2[0:1,1:3]

array([[1, 2]])

In [19]:
np2[:,::2]

array([[6, 2, 3, 6, 4],
       [9, 6, 5, 2, 3]])

In [20]:
np3=np.random.randint(1,20,size=(1,10))
np3

array([[ 4,  2,  1, 19, 19, 17,  7, 14, 10, 14]])

In [21]:
#Numpy Universal Functions

##Square root of each elements
np.sqrt(np3)

array([[2.        , 1.41421356, 1.        , 4.35889894, 4.35889894,
        4.12310563, 2.64575131, 3.74165739, 3.16227766, 3.74165739]])

In [22]:
#Absolute Value
np.absolute(np3)

array([[ 4,  2,  1, 19, 19, 17,  7, 14, 10, 14]])

In [23]:
#Exponents
np.exp(np3)

array([[5.45981500e+01, 7.38905610e+00, 2.71828183e+00, 1.78482301e+08,
        1.78482301e+08, 2.41549528e+07, 1.09663316e+03, 1.20260428e+06,
        2.20264658e+04, 1.20260428e+06]])

In [24]:
#Min and Max

print(np.min(np3))
print(np.max(np3))

1
19


In [25]:
#Sign Positive or Negative

print(np.sign(np3))

[[1 1 1 1 1 1 1 1 1 1]]


In [26]:
#Trig sin cos log

print(np.sin(np3))
print(np.cos(np3))
print(np.log(np3))

[[-0.7568025   0.90929743  0.84147098  0.14987721  0.14987721 -0.96139749
   0.6569866   0.99060736 -0.54402111  0.99060736]]
[[-0.65364362 -0.41614684  0.54030231  0.98870462  0.98870462 -0.27516334
   0.75390225  0.13673722 -0.83907153  0.13673722]]
[[1.38629436 0.69314718 0.         2.94443898 2.94443898 2.83321334
  1.94591015 2.63905733 2.30258509 2.63905733]]


In [27]:
#Copy vs View
random.seed(33)
np4=np.random.randint(1,15,size=(10))
np4

array([ 5,  8,  9,  3,  3, 10, 10,  4,  7, 14])

In [28]:
#Create a View
np5=np4.view()
print(f'Original array{np4}')
print(f'View          {np5}')
np5[0]=0
print(f'Original array{np4}')
print(f'Changed array {np5}')

Original array[ 5  8  9  3  3 10 10  4  7 14]
View          [ 5  8  9  3  3 10 10  4  7 14]
Original array[ 0  8  9  3  3 10 10  4  7 14]
Changed array [ 0  8  9  3  3 10 10  4  7 14]


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [29]:
#Create a Copy
np6=np4.copy()
print(f'Original array{np4}')
print(f'Copy array    {np6}')
np6[0]=33
print(f'Original array{np4}')
print(f'Changed array {np6}') 

Original array[ 0  8  9  3  3 10 10  4  7 14]
Copy array    [ 0  8  9  3  3 10 10  4  7 14]
Original array[ 0  8  9  3  3 10 10  4  7 14]
Changed array [33  8  9  3  3 10 10  4  7 14]


In [30]:
#Create 1-D Numpy Array and Get Shape

np1=np.random.randint(1,11,size=(10))
print(np1)
print(np1.shape)


[4 4 2 8 7 1 1 7 7 1]
(10,)


In [31]:
#Create 2-D Numpy Array and Get Shape

np2=np.random.randint(1,11,size=(2,6))
print(np2)
print(np2.shape)

[[ 5  9  9  4  8 10]
 [ 4  4  8  4  8  3]]
(2, 6)


In [32]:
#Reshape 2D
print(np1)
print(f'Reshape above list to 2,5')
np3=np1.reshape(2,5)
np3

[4 4 2 8 7 1 1 7 7 1]
Reshape above list to 2,5


array([[4, 4, 2, 8, 7],
       [1, 1, 7, 7, 1]])

In [33]:
#Reshape 3D

np4=np2.reshape(2,3,2)
print(np2)
print(np4)

[[ 5  9  9  4  8 10]
 [ 4  4  8  4  8  3]]
[[[ 5  9]
  [ 9  4]
  [ 8 10]]

 [[ 4  4]
  [ 8  4]
  [ 8  3]]]


In [34]:
#Flatten to 1-D

np5=np4.reshape(-1)
np5

array([ 5,  9,  9,  4,  8, 10,  4,  4,  8,  4,  8,  3])

In [35]:
np6=np.random.randint(1,101,size=(3,6))
np6

array([[82,  4, 23, 27, 33, 49],
       [53, 26, 79, 31, 54, 91],
       [56, 76, 61,  2, 63, 50]])

In [36]:
#iterate array
for x in np.nditer(np6):
    print(x)

82
4
23
27
33
49
53
26
79
31
54
91
56
76
61
2
63
50


In [37]:
#Sort--Nummerical
np7=np.random.randint(1,15,size=(10))
print(np7)
print(np.sort(np7))

[ 5  2 12  2 13  9 11  5  9 13]
[ 2  2  5  5  9  9 11 12 13 13]


In [38]:
#Sort--Alphabetical

np8=np.array(['Melbin','Albin','Akhil','Nevin','Jeffin','Alan','Vinil'])
print(np8)
print(np.sort(np8))

['Melbin' 'Albin' 'Akhil' 'Nevin' 'Jeffin' 'Alan' 'Vinil']
['Akhil' 'Alan' 'Albin' 'Jeffin' 'Melbin' 'Nevin' 'Vinil']


In [39]:
#Boolean T/F

np9=np.array([True,False,False,True,True,False])
print(np9)
print(np.sort(np9))

[ True False False  True  True False]
[False False False  True  True  True]


Original doesn't get changed when we sort original array/list

It's just returning a copy

In [40]:
#3-D array sort
n1=np.random.randint(1,40,size=(3,6))
print(n1)
print(f'Sorted Array{np.sort(n1)}')

[[29 22  9  1 26 14]
 [24 26 23 10  6 11]
 [28 33 20 33 17 29]]
Sorted Array[[ 1  9 14 22 26 29]
 [ 6 10 11 23 24 26]
 [17 20 28 29 33 33]]


In [41]:
#Search 
random.seed(12)
n2=np.random.randint(1,40,size=(10))
print(n2)
#print(np.where(n2[4]))
#or print(np.where(n2==4))
x=np.where(n2==4)
print(x[0])

[12 28  7  3  4  4 13 23  6 14]
[4 5]


In [42]:
#Return Even items

y=np.where(n2%2==0)
print(n2)
print(y[0])

[12 28  7  3  4  4 13 23  6 14]
[0 1 4 5 8 9]


In [43]:
#Return Odd items

z=np.where(n2%2!=0)
print(n2)
print(z[0])

[12 28  7  3  4  4 13 23  6 14]
[2 3 6 7]


In [45]:
#Filterning Numpy array with Boolean Index Lists
n3=np.array([1,2,3,4,5,6,7,8,9])
x=[True,False,True,True,True,False,False,False,True]
print(n3)
print(n3[x])

[1 2 3 4 5 6 7 8 9]
[1 3 4 5 9]


In [48]:
filter=[]
for x in n3:
    if x %3==0:
        filter.append(True)
    else:
        filter.append(False)

print(n3)
print(filter)
print(n3[filter])

[1 2 3 4 5 6 7 8 9]
[False, False, True, False, False, True, False, False, True]
[3 6 9]


In [49]:
random.seed(12)
n4=np.random.randint(1,102,size=(10,10))
n4

array([[ 76,  28,   7,   3,   4,  68,  77,  49,  23,  50],
       [ 53,   6,  14,  90,  35,  76,  75,   1,  77,  14],
       [ 83,  90,  36,  63, 101,  36,  34,  31,  64,  97],
       [ 19,  87,  51,  81,  85,   7,  74,  46,  31,  33],
       [ 28,  60,  90,  60,  89,  80,  26,  98,  57,   5],
       [ 97,  69,  66,  45,  38,  76,  69,  54,  76,  54],
       [ 48,  61,  97,  43,  71,  71,  68,   3,  29,  75],
       [ 59,  60,  85, 100,  55,  56,  85,  98,  21,  30],
       [ 70,  52,  44,  33,  44,  19,  71,  92,  35, 101],
       [ 54,  59,   1,  38,  21,  81,  68,  88,  58,  55]])

In [55]:
n4[n4<=50]=0
n4[n4>50]=1
print(n4)

[[1 0 0 0 0 1 1 0 0 0]
 [1 0 0 1 0 1 1 0 1 0]
 [1 1 0 1 1 0 0 0 1 1]
 [0 1 1 1 1 0 1 0 0 0]
 [0 1 1 1 1 1 0 1 1 0]
 [1 1 1 0 0 1 1 1 1 1]
 [0 1 1 0 1 1 1 0 0 1]
 [1 1 1 1 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1 0 1]
 [1 1 0 0 0 1 1 1 1 1]]


In [58]:
#Shortcut!
print(n3)
filtered = n3%2 == 0
print(filtered)
print(n3[filtered])

[1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False]
[2 4 6 8]
