In [1]:
#Addition

In [2]:
row=int (input("Enter the row number:"))
col=int(input("Enter the column number:"))

print("Enter the elements for matrix:")
matrix1=[[int(input()) for i in range(col)] for j in range(row)]
print("Matrix 1")

for i in range(row):
    for j in range(col):
        print(matrix1[i][j], end=" ")
    print()

matrix2=[[int(input()) for i in range(col)] for j in range(row)]
print("Matrix 2")
for i in range(row):
    for j in range(col):
        print(matrix2[i][j],end=" ")
    print()
    
result=[[0 for i in range(col)] for j in range(row)]

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j]=matrix1[i][j] + matrix2[i][j]

print("Result:")
for i in range(row):
    for j in range(col):
        print(result[i][j],end=" ")
    print()

Enter the row number:2
Enter the column number:2
Enter the elements for matrix:
1
2
3
4
Matrix 1
1 2 
3 4 
6
7
8
9
Matrix 2
6 7 
8 9 
Result:
7 9 
11 13 


In [3]:
#Substratioin

In [8]:
row =int(input("Enter number of rows:"))
col=int(input("Enter nnumber of columns:"))

print("Enter the elements:")

matrix3=[[int(input()) for i in range(col)] for j in range(row)]
print("Matrix A")
for i in range(row):
    for j in range(col):
        print(matrix3[i][j],end=" ")
    print()
    
matrix4=[[int(input()) for i in range(col)] for j in range(row)]

print("Matrix B")

for i in range(row):
    for j in range(col):
        print(matrix4[i][j],end=" ")
    print()
    
result=[[0 for i in range(col)] for j in range(row)]

for i in range(len(matrix3)):
    for j in range(len(matrix3[0])):
        result[i][j]=matrix3[i][j] - matrix4[i][j]

print("Result:")
for i in range(row):
    for j in range(col):
        print(result[i][j],end=" ")
    print()

Enter number of rows:2
Enter nnumber of columns:2
Enter the elements:
1
2
3
4
Matrix A
1 2 
3 4 
1
2
3
4
Matrix B
1 2 
3 4 
Result:
0 0 
0 0 


In [ ]:
#Multipication

In [10]:
p=int(input("Enter the ROW number fro Matrix 1:"))
q=int(input("Enter the COLUMN number for Matrix 2:"))
n=int(input("Enter the COLUMN number for Matrix 1 or ROW number for Matrix 2:"))

print("Enter element for Matrix 1:")
matrix1=[[int(input()) for i in range(n)] for j in range(p)]
print("Matrix 1")
for i in range(p):
    for j in range(n):
        print(matrix1[i][j],end=" ")
    print()
print("Enter element for Matrix 2:")
matrix2=[[int(input()) for i in range(q)] for j in range(n)]
print("Matrix 2")
for i in range(n):
    for j in range(q):
        print(matrix2[i][j],end=" ")
    print()
result=[[0 for i in range(q)] for j in range(p)]
for i in range(p):
    for j in range(q):
        for k in range(n):
            result[i][j]=result[i][j] + matrix1[i][k] * matrix2[k][j]

print("Result:")

for i in range(p):
    for j in range(q):
        print(result[i][j],end=" ")
    print()

Enter the ROW number fro Matrix 1:2
Enter the COLUMN number for Matrix 2:2
Enter the COLUMN number for Matrix 1 or ROW number for Matrix 2:2
Enter element for Matrix 1:
1
2
3
4
Matrix 1
1 2 
3 4 
Enter element for Matrix 2:
1
2
3
4
Matrix 2
1 2 
3 4 
Result:
7 10 
15 22 


In [1]:
import numpy as np

# Define the matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Perform matrix multiplication
matrix_product = np.dot(A, B)

# Perform dot product (flatten both matrices and then take the dot product)
dot_product = np.dot(A.flatten(), B.flatten())

print("Matrix multiplication result:")
print(matrix_product)

print("\nDot product result:")
print(dot_product)


Matrix multiplication result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Dot product result:
165


In [3]:
import pandas as pd
import numpy as np
pd.Series([1, 3, 5, np.nan, 6, 8])

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64